### ISSUE TITLE
Webpack peer dependency

### ISSUE THREAD

**Issue by dmihal** [jhen0409/webpack-httpolyglot-server#4]
The webpack peerDependency doesn't allow Webpack 2.0. It looks like the package was made compatible with Webpack 2 in #2, so the `package.json` should be updated to allow Webpack 2.

**Comment by jhen0409** [comment]
Sorry for long delay, it's fixed in https://github.com/jhen0409/webpack-httpolyglot-server/commit/2d869d4a6d731cb20d672d94d48e6eaeb6737045.
